application: trainerbuddy
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: web/js

- url: /style
  static_dir: web/style

- url: /user/.*
  script: controllers/master.py

- url: /user
  script: controllers/master.py
  
- url: /json/.*
  script: controllers/master.py
  secure: always

- url: /.*
  script: controllers/home.py
